config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations", sessions: 'sessions', invitations: 'users/invitations' }
  root 'home#index'
  resources :organizations do
    resources :projects do
      resources :members, only: [:index, :destroy, :create]
    end
  end
  resources :artifacts
  post "checkout/create", to: "checkout#create", as: "checkout_create"
  post "billing_portal/create", to: "billing_portal#create", as: "billing_portal_create"
  resources :webhooks, only: [:create]
  get 'features', to: "home#features"
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :user_project
  has_many :users, through: :user_project
  has_many :members
  has_many :users, through: :members
  belongs_to :organization
  validates :expected_completion_date, presence: true
  validates :title, presence: true, length: {minimum: 3, maximum: 25}
  validates :details, presence: true, length: {minimum: 5, maximum: 125}
  validate :expected_completion_date_greater_then_today
  has_many :artifacts, dependent: :destroy

  def self.by_user_plan_and_organization(org_id, user)
    org = Organization.find(org_id)
    if org.plan == 'premium'
      if user.admin?
        org.projects
      else
        user.projects.where(organization_id: org.id)
      end
    else
      if user.admin
        org.projects.order(:id).limit(1)
      else
        user.projects.where(organization_id: org.id).order(:id).limit(1)
      end
    end
  end

  def self.set_project_check(project_id, organization)
    if organization.plan == 'free'
      return organization.projects[0]
    else
      return organization.projects.find(project_id)
    end
  end

  def expected_completion_date_greater_then_today
    unless !expected_completion_date.present? || expected_completion_date > Time.now
      errors.add(:expected_completion_date, "must be greater than today")
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy, :new, :create]
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :verify_organization
  before_action :free_plan_can_only_have_one_project, only: [:new, :create]
  before_action :request_admin, only: [ :new, :create, :update, :edit, :destroy ]

  def index
    @projects = Project.by_user_plan_and_organization(params[:organization_id], current_user)
  end

  def show
    session[:project_id] = @project.id
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)

    @project.organization_id = params[:organization_id]
    if @project.save
      flash[:notice] = "Project created successfully"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def update
    if @project.update(project_params)
      flash[:notice] = "Project was successfully updated"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    @project.destroy
    flash[:notice] = "Project was successfully destroyed"
    redirect_to root_path
  end

  private

  def set_project
    @project = Project.set_project_check(params[:id], @organization)
  end

  def project_params
    params.require(:project).permit(:title, :details, :expected_completion_date)
  end

  def set_organization
    @organization = Organization.find(params[:organization_id])
  end

  def verify_organization
    unless params[:organization_id] == current_user.organizations[0].id.to_s
      redirect_to root_path, notice: 'You are not authorized to access not your organization'
    end
  end

  def free_plan_can_only_have_one_project
    if !(@organization.projects.count <= 1) && @organization.plan == 'free'
      redirect_to root_path, notice: 'Free plans can not have more than one project'
    end
  end


end

app/views/projects/_form.html.erb
<%= form_for [@organization, @project] do |f| %>

  <% if @project.errors.any? %>
    <div class="container alert alert-danger">
      <div class="panel-body">
        <ul>
          <% @project.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= f.label :title, class: "form-label" %>
    <%= f.text_field :title,
                     class: "form-control",
                     placeholder: "Enter your title" %>
  </div>

  <div class="field mb-3">
    <%= f.label :details, class: "form-label" %>
    <%= f.text_field :details,
                     class: "form-control",
                     placeholder: "Enter your details" %>
  </div>

  <div class="field mb-3">
    <%= f.label :expected_completion_date, class: "form-label" %>
    <%= f.date_field :expected_completion_date, class: 'form-control' %>
  </div>

  <br />

  <%= f.hidden_field :organization_id, value: params[:organization_id], class: 'form-control' %>

  <%= f.submit nil, class: 'btn btn-primary' %>
  <%= link_to "Cancel",
              root_path,
              class: 'btn btn-default' %>

<% end %>

app/views/projects/_list.html.erb
<div class="container">
  <div class="page-header">
  <h1>Projects</h1>
  </div>
  <% if @projects.size > 0 %>
    <table class="table table-striped">
      <tr>
        <th scope="col">Title</th>
        <th scope="col">Details</th>
        <th scope="col">Expected completion date</th>
        <% if current_user.admin? %>
          <th scope="col">Actions</th>
        <% end %>
      </tr>

      <% @projects.each do |project| %>
        <tr>
          <td><%= link_to truncate(project.title, length: 20),
                          organization_project_path(project, organization_id: @org.id),
                          class: 'text-decoration-none' %></td>
          <td><%= truncate(project.details, length: 20) %></td>
          <td><%= project.expected_completion_date %></td>
          <% if current_user.admin? %>
            <td>
              <%= link_to "Edit",
                          edit_organization_project_path(project, organization_id: @org.id),
                          :class => 'btn btn-secondary' %>
              <%= link_to 'Edit Users', organization_project_members_path(project, organization_id: @org.id),
                          :class => 'btn btn-primary' %>
              <%= link_to "Delete",
                          organization_project_path(project, organization_id: @org.id),
                          :method => :delete,
                          :data => { :confirm => "Are you sure?" },
                          :class => 'btn btn-danger' %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </table>
  <% else %>
    <p class="lead">You don't have any projects</p>
  <% end %>

  <% if (@org.can_create_projects?) && !current_user.invited_by_id? %>
    <%= link_to 'New Project', new_organization_project_path(organization_id: @org.id),
                :class => 'btn btn-primary' %>
  <% end %>
</div>

app/views/projects/edit.html.erb
<div class="container">
  <div class="page-header">
    <h1>Edit Project</h1>
  </div>
  <%= render 'form' %>
</div>

app/views/projects/new.html.erb
<div class="container">
  <div class="page-header">
    <h1>New Project</h1>
  </div>
  <%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div class="container">
  <div>
    <h3><%= @project.title %></h3>
    <h3><small class="fw-light">Organization - <%= organization_name %></small></h3>
  </div>

  <hr>

  <table class="table table-sm table-borderless project-table mb-5">
    <tr>
      <td class="fw-bold">Title:</td>
      <td><%= @project.title %></td>
    </tr>
    <tr>
      <td class="fw-bold">Details:</td>
      <td><%= @project.details %></td>
    </tr>
    <tr>
      <td class="fw-bold">Expected completion date:</td>
      <td><%= @project.expected_completion_date %></td>
    </tr>
    <tr>
      <td class="fw-bold">Organization</td>
      <td><%= organization_name %></td>
    </tr>
  </table>

  <h3>Artifacts</h3>
  <%= render 'artifacts/list', artifacts: @project.artifacts%> <br> <br>

  <div class="d-inline-flex flex-column">
    <div class="mb-1">
      <%= link_to 'Edit Members', organization_project_members_path(@project, organization_id: @project.organization_id),
    :class => 'btn btn-outline-primary' %>
    </div>
    <div class="mb-1">
      <%= link_to "Edit Project",
                  edit_organization_project_path(project: @project, organization: @project.organization_id),
                  :class => 'btn btn-primary' %>
      <%= link_to 'Destroy Project',
                  organization_project_path(@project, organization_id: @project.organization_id),
                  :method => 'delete',
                  :data => { :confirm => 'Are you sure?' },
                  :class => 'btn btn-danger' %>
    </div>
    <div>
      <%= link_to '< Back', root_path, :class => 'btn btn-secondary'  %>
    </div>
  </div>
</div>