config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations", sessions: 'sessions', invitations: 'users/invitations' }
  root 'home#index'
  resources :organizations do
    resources :projects do
      resources :members, only: [:index, :destroy, :create]
    end
  end
  resources :artifacts
  post "checkout/create", to: "checkout#create", as: "checkout_create"
  post "billing_portal/create", to: "billing_portal#create", as: "billing_portal_create"
  resources :webhooks, only: [:create]
  get 'features', to: "home#features"
end

app/models/artifact.rb
class Artifact < ActiveRecord::Base
  belongs_to :project
  has_one_attached :file

  validates :name,
            presence: true
  validates :file,
            attached: true,
            size: { between: 1.byte..10.megabytes, message: 'is not given between size' }
end

app/controllers/artifacts_controller.rb
class ArtifactsController < ApplicationController
  before_action :set_artifact, only: [:show, :edit, :destroy]
  before_action :set_organization, only: [:new]

  def index
    @artifacts = Artifact.all
  end

  def show
  end

  def new
    @artifact = Artifact.new
    @artifact.project_id = session[:project_id]
  end

  def edit
  end

  def create
    @artifact = Artifact.new(artifact_params)

    if @artifact.save
      @artifact.update(key: @artifact.file.url)
      flash[:notice] = "Artifact created successfully"
      redirect_to organization_project_path(organization_id: session[:organization_id], id: @artifact.project_id)
    else
      render 'new'
    end
  end

  def destroy
    @artifact.destroy
    redirect_to organization_project_path(organization_id: session[:organization_id], id: @artifact.project_id)
  end


  private

  def set_artifact
    @artifact = Artifact.find(params[:id])
  end

  def artifact_params
    params.require(:artifact).permit(:name, :project_id, :file)
  end

  def set_organization
    @organization = Organization.find(session[:organization_id])
  end
end

app/views/artifacts/_form.html.erb
<%= form_with model: @artifact do |f| %>
  <% if @artifact.errors.any? %>
    <div class="container alert alert-danger">
      <div class="panel-body">
        <ul>
          <% @artifact.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= f.label :name, class: "form-label" %>
    <%= f.text_field :name,
                     class: "form-control",
                     placeholder: "Enter artifact name" %>
  </div>

  <div class="field mb-3">
    <%= f.label :file, class: "form-label" %>
    <%= f.file_field :file,
                     class: "form-control",
                     placeholder: "Choose file" %>
  </div>


  <%= f.hidden_field :project_id %>

  <%= f.submit nil, class: 'btn btn-primary' %>
  <%= link_to "Cancel",
              organization_project_path(organization_id: session[:organization_id], id: @artifact.project_id),
              class: 'btn btn-default' %>
<% end %>

app/views/artifacts/_list.html.erb
<div class="container">
    <table class="table table-striped">
      <tr>
        <th>Name</th>
        <th>Key</th>
        <th>Action</th>
      </tr>

      <% artifacts.each do |artifact| %>
        <tr>
          <td><%= link_to artifact.name,
                          artifact_path(artifact), class: 'text-decoration-none' %></td>
          <td><%= link_to "Open", artifact.key, target: '_blank' %></td>
          <td>
            <%= link_to "Delete",
                        artifact_path(artifact),
                        :method => :delete,
                        :data => { :confirm => "Are you sure?" },
                        :class => 'btn btn-danger' %>
          </td>
        </tr>
      <% end %>
    </table>

    <%= link_to 'New Artifact', new_artifact_path,
                :class => 'btn btn-success' %>
</div>

app/views/artifacts/index.html.erb
<%= render 'artifacts/list', artifacts: @project.artifacts%>

app/views/artifacts/new.html.erb
<div class="container">
  <div class="page-header">
    <h1>New Artifact</h1>
  </div>
  <%= render 'form' %>
</div>

app/views/artifacts/show.html.erb
<div class="container">
  <div>
    <h3><%= @artifact.name %></h3>
    <h3><small class="fw-light">Organization - <%= organization_name %></small></h3>
  </div>

  <hr>

  <table class="table table-sm table-borderless artifact-table-show mb-5">
    <tr>
      <td class="fw-bold">Name:</td>
      <td><%= @artifact.name %></td>
    </tr>
    <tr>
      <td class="fw-bold">Key:</td>
      <td><%= link_to 'Open File', @artifact.key, target: '_blank', class: 'text-decoration-none' %></td>
    </tr>
  </table>

  <%= link_to '< Back to Project',
              organization_project_path(organization_id: session[:organization_id], id: @artifact.project_id),
              :class => 'btn btn-secondary'  %>
  <%= link_to "Delete",
              artifact_path(@artifact),
              :method => :delete,
              :data => { :confirm => "Are you sure?" },
              :class => 'btn btn-danger' %>
</div>