config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations", sessions: 'sessions', invitations: 'users/invitations' }
  root 'home#index'
  resources :organizations do
    resources :projects do
      resources :members, only: [:index, :destroy, :create]
    end
  end
  resources :artifacts
  post "checkout/create", to: "checkout#create", as: "checkout_create"
  post "billing_portal/create", to: "billing_portal#create", as: "billing_portal_create"
  resources :webhooks, only: [:create]
  get 'features', to: "home#features"
end

app/views/layouts/_header.html.erb
<header class="p-3 bg-dark text-white mb-3">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
          <use xlink:href="#bootstrap"></use>
        </svg>
      </a>

      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><%= link_to 'Home', root_path, class: 'nav-link px-2 text-secondary' %></li>
        <li><%= link_to "Features", features_path, class: "nav-link px-2 text-white" %></li>
        <% if user_signed_in? && current_user.admin? %>
          <%= link_to "Add new member", new_user_invitation_path, class: "nav-link px-2 text-white" %>
          <div class="dropdown">
            <a class="nav-link px-2 text-white dropdown-toggle"
               href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
              Finance
            </a>

            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <li><%= link_to "Billing Portal", billing_portal_create_path,
                              method: :post,
                              class: "dropdown-item" %></li>
            </ul>
          </div>
        <% end %>
      </ul>

      <div class="text-end">
        <% if user_signed_in? %>
          <% if current_user.admin? && current_user.organizations[0].plan == 'free' %>
            <%= link_to "Update Plan", checkout_create_path,
                        method: :post,
                        remote: true,
                        class: "btn btn-success me-5",
                        id: 'premium'%>
          <% end %>
          <%= link_to 'Edit', edit_user_registration_path, class: 'btn btn-warning me-2' %>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-danger me-2' %>
      <% else %>
          <%= link_to 'Login', new_user_session_path, class: 'btn btn-outline-light me-2' %>
          <% unless current_page?(root_path) %>
            <%= link_to 'Sign-up', new_user_registration_path, class: 'btn btn-warning' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_messages.html.erb
<% if flash.any? %>
<% flash.each do |type, msg| %>
    <div class="container alert alert-<%= type == "notice" ? "success" : "danger" %> alert-dismissible">
        <div>
          <%= msg %>
        </div>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SaasProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://js.stripe.com/v3/"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>